name: "ATPsolar Login API"
version: "1.4"
slug: "atpsolar_login_api"
description: "FastAPI backend cho quyen lay nguoi dung trong InfluxDB"
arch:
  - aarch64
startup: application
boot: auto
init: false
ports:
  8000/tcp: 8000
environment:
  MYSQL_HOST: "addon_core_mariadb"
  MYSQL_PORT: "3306"
  MYSQL_USER: "hieunn"
  MYSQL_PASSWORD: "Hieu987456321#$"
  MYSQL_DATABASE: "atpsolar"
